spring:
  application:
    name: bills
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog-master.xml

path:
  to:
    folder:
      with:
        bills: /bills/images

server:
  port: 8080

host: localhost